repos:
- repo: git://github.com/eana/pre-commit-terraform
  rev: v1.45.0
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
    - id: terraform_docs
- repo: https://github.com/eana/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: check-yaml
